### ISSUE TITLE
LIbrary Works in Debug Only and Throws an Error in Release Build

### ISSUE THREAD

**Issue by H-Shafiei** [ArioAtlas/react-native-cafe-bazaar#23]
Salam,

Thanks for your library.

I am trying to use your library for my app and I have tested it in several scenarios in debug mode while developing and everything works fine.

The problem is when I try to build a release version of the app to deploy it to the store, the library does not work (It doesn't load the owned items, doesn't purchase or doesn't do anything else).

I first thought it was my Proguard rules. Then I added `-keep class com.android.vending.billing` to my Proguard rules (it is stated [here](https://developers.cafebazaar.ir/fa/docs/iab/security/)) but the results were the same:(

This is my adblogcat:

```
04-13 05:53:27.209  4114  4187 I SurfaceFlinger: id=15625 Removed Dim Layer for - Task=24438#0 (0/68)
04-13 05:53:27.226  4114  4114 I Layer   : id=15625 onRemoved Dim Layer for - Task=24438#0
04-13 05:53:27.226  4114  4187 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=24438#0 [s.what : 10000]
04-13 05:53:27.226  4114  4187 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=24438#0
04-13 05:53:27.226  4114  4187 I SurfaceFlinger: id=15629 Removed Surface(name=Dim Layer for - Task=24438)/@0x769f8c4 - animation-leash#0 (1/67)
04-13 05:53:27.227  4556  4644 I WindowManager: reset, Reparenting to original parent, shouldDeferScheduleAnimation=false, destroyLeash=true, surface=Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318, parent=Surface(name=Task=24438)/@0x310a7d2, parentNativeHandle=android.os.BinderProxy@bfacacf, caller=com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97 com.android.server.wm.-$$Lambda$SurfaceAnimator$SIBia0mND666K8lMCPsoid8pUTI.run:4 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1:104 com.android.server.wm.-$$Lambda$SurfaceAnimator$vdRZk66hQVbQCvVXEaQCT1kVmFc.onAnimationFinished:4 com.android.server.wm.LocalAnimationAdapter.lambda$startAnimation$0:65
04-13 05:53:27.227  4556  4644 D SurfaceControl: reparent is called, sc=Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318, newParentHandle=android.os.BinderProxy@bfacacf, transaction=android.view.SurfaceControl$Transaction@9f16663
04-13 05:53:27.227  4556  4644 D SurfaceControl: destroy(transaction), animation-leash is destroyed, sc=Surface(name=Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318 - animation-leash)/@0x2d021d, transaction=android.view.SurfaceControl$Transaction@9f16663, caller=com.android.server.wm.SurfaceAnimator.reset:338 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97 com.android.server.wm.-$$Lambda$SurfaceAnimator$SIBia0mND666K8lMCPsoid8pUTI.run:4 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1:104 com.android.server.wm.-$$Lambda$SurfaceAnimator$vdRZk66hQVbQCvVXEaQCT1kVmFc.onAnimationFinished:4 com.android.server.wm.LocalAnimationAdapter.lambda$startAnimation$0:65 com.android.server.wm.-$$Lambda$LocalAnimationAdapter$X--EomqUvw4qy89IeeTFTH7aCMo.run:4
04-13 05:53:27.228  4556  4644 V WindowManager: Setting visibility of Window{862213d u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity EXITING}: false, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:615 com.android.server.wm.AppWindowToken.setClientHidden:460 com.android.server.wm.AppWindowToken.onAnimationFinished:2390 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:100
04-13 05:53:27.228  4556  4644 E WindowManager: win=Window{862213d u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5430 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2405 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2
04-13 05:53:27.228  4556  4644 I WindowManager: Destroying surface Surface(name=com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity[16361])/@0x9ffd02c called by com.android.server.wm.WindowStateAnimator.destroySurface:1880 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:838 com.android.server.wm.WindowState.destroySurfaceUnchecked:3840 com.android.server.wm.WindowState.destroySurface:3821 com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5430 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2
04-13 05:53:27.228  4114  4187 I SurfaceFlinger: id=15623 Removed com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity[16361]#1 (0/66)
04-13 05:53:27.228 16361 16361 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
04-13 05:53:27.229 16361 16361 W System.err: 	at android.view.ViewRootImpl.getHostVisibility(ViewRootImpl.java:1809)
04-13 05:53:27.229 16361 16361 W System.err: 	at android.view.ViewRootImpl.handleAppVisibility(ViewRootImpl.java:1445)
04-13 05:53:27.229 16361 16361 W System.err: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4829)
04-13 05:53:27.229 16361 16361 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-13 05:53:27.229 16361 16361 W System.err: 	at android.os.Looper.loop(Looper.java:214)
04-13 05:53:27.229 16361 16361 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7099)
04-13 05:53:27.229 16361 16361 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 05:53:27.229 16361 16361 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-13 05:53:27.229 16361 16361 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
04-13 05:53:27.232  4556 12881 D ConnectivityService: filterNetworkStateForUid() uid: 10185, pid: 16361
04-13 05:53:27.232  4556 12881 D ConnectivityService: isNetworkWithLinkPropertiesBlocked: uid=10185, vpn=DISCONNECTED,false
04-13 05:53:27.232  4114  5190 W SurfaceFlinger: Attempting to set client state on removed layer: com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity[16361]#1 [s.what : 40]
04-13 05:53:27.232  4114  5190 D Layer   : [AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}}#0]::reparent oldParent:[Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318 - animation-leash#0], newParent:[Task=24438#0]
04-13 05:53:27.232  4114  5190 I SurfaceFlinger: id=15621 Removed 862213d com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity#0 (0/65)
04-13 05:53:27.232  4114  5190 I SurfaceFlinger: id=15628 Removed Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318 - animation-leash#0 (0/64)
04-13 05:53:27.232  4556 12881 D ConnectivityService: filterNetworkStateForUid() uid: 10185, pid: 16361, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
04-13 05:53:27.232  4114  5190 W SurfaceFlinger: Attempting to destroy on removed layer: com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity[16361]#1
04-13 05:53:27.233  4556  4556 D FreeformController: Fail to invalid task id :  -1
04-13 05:53:27.233  4556  4644 I WindowManager: Cancelling animation restarting=false, leash=null, surface=Surface(name=AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}})/@0x1afc318, parent=Surface(name=Task=24438)/@0x310a7d2
04-13 05:53:27.236  4114  5190 I SurfaceFlinger: id=15619 Removed AppWindowToken{740b6d0 token=Token{d20b693 ActivityRecord{c339f82 u0 com.farsitel.bazaar/ir.cafebazaar.ui.pardakht.PaymentActivity t24438}}}#0 (1/63)
```

**Comment by mdehghani65** [comment]
you may also check out [this](https://github.com/ArioAtlas/react-native-cafe-bazaar/issues/13) issue

**Comment by arashmilani** [comment]
This library is not being actively updated. You might want to use the [RN library of the cafebazaar itself](https://github.com/cafebazaar/react-native-poolakey).
